on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |  
            Hi there! 👋

            Thanks for your PR. Please check if your code changes in this PR are references on https://tutorials.solace.dev/

            If they are, please update:

            1. The commit number in the [gatsby-config.js](https://github.com/SolaceDev/solace-dev-tutorials/blob/master/gatsby-config.js) file
            1. Update the lines of code referenced in `src/pages/tutorials/{language}/{tutorial.md}` file in the `embed:{Lang}-Samples/{path/to/file}#L{start_line}-{end_line}` section
          repo-token: ${{ secrets.PAT }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default