name: Config Push
on:
  pull_request: 
    branches: [ master ]

env: 
  APPLICATION_VERSION_ID: puu886to6kd
  EVENT_MESH_NAME: us-central-solace-Prod
  PREVIEW_ONLY: TRUE

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Deploy Application Version ID
        uses: SolaceDev/solace-ep-config-push
        with:
          SOLACE_CLOUD_TOKEN: ${{ secrets.SOLACE_CLOUD_TOKEN }}
          APPLICATION_VERSION_ID: ${{ env.APPLICATION_VERSION_ID }}
          EVENT_MESH_NAME: ${{ env.EVENT_MESH_NAME }}
          PREVIEW_ONLY: ${{ env.PREVIEW_ONLY }}