name: Validate markdown file
on:
  pull_request: 
    branches: [ master ]

env:
  CANCEL_WORKFLOW: false

jobs:
  claat-export: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codelabs repo
        uses: actions/checkout@v3
        with:
          path: codelabs
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install claat
        run: |
          go install github.com/googlecodelabs/tools/claat@latest

    # Get all files in commit
      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: Validate markdown file using claat
        run: |
          markdownFiles=()
          for changed_file in ${{ steps.files.outputs.all }}
          do
            if [[ ( ${changed_file} == *.html ) ]]
            then
              echo "Do not commit any html or json files!"
              exit 1
            fi

            if [[ ( ${changed_file} == *.md ) ]]
            then
              markdownFiles+=("$changed_file")
              claat export -o ../../codelabs/ $changed_file
            fi
          done

          if [ ${#markdownFiles[@]} -eq 0 ]; then
            echo "Cancel workflow. No markdown found!"
            echo "CANCEL_WORKFLOW=true" >> $GITHUB_ENV
          fi

      - name: Cancel Workflow if no asyncAPI file present in PR
        if: env.CANCEL_WORKFLOW == 'true'
        uses: andymckay/cancel-action@0.2

      - name: Checkout codelabs Site repo
        uses: actions/checkout@v3
        with:
          repository: SolaceDev/solace-dev-codelabs-site
          path: codelabs-site
          submodules: recursive
      
      - name: Install node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
        
      - name: build site with new files
        run: | 
          echo "YOLO"
          cp -r codelabs/codelabs codelabs-site/site/solace-dev-codelabs/codelabs
          ls codelabs-site/site/solace-dev-codelabs/codelabs