name: Broken Links Checker
on:
  push: 
    branches: [ master ]

jobs:
  Broken_Link_Checker:
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2