name: Claat Export
on:
  push:
    paths:
      - markdown/**

jobs:
  Claat-Export:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      
      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          path: main

      - name: Checkout claat repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/google-tools
          path: google-tools
      
      - name: Build claat
        run: cd google-tools/claat; go build .
      
      - name: Update PATH
        run: cd google-tools/claat; export PATH=$PATH:$pwd
      
      - name: Echo Path
        run: echo $PATH

      - name: Export file
        run: cd main/markdown/dt-otel; claat export dt-otel.md

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"