name: PR Comment
on:
  pull_request:

jobs:
  pr-comment:
    name: Add guidelines comment
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            test
          repo-token: ${{ secrets.PAT }}