name: PR Comment
on:
  pull_request: 
    branches: [ master ]
    
jobs:
  comment:
    name: Add checkout and pull commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          filename: template.md