name: Context trigger
on:
  push: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - uses: actions/checkout@v3
      
      - name: Checkout terraform configuration repo
        uses: actions/checkout@v2
        with:
          repository: TamimiGitHub/solace-terraform-provisioning
          path: terraform
        
      - name: Install dependencies
        run: cd terraform; npm install
      
      - name: Promote application 
        run: |
          cd terraform
          npm run promote -- -f ../asyncapi/yolo.json -mes PROD-Kafka