name: Context trigger
on:
  push: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - uses: actions/checkout@v3
      
      - name: Checkout terraform configuration repo
        uses: actions/checkout@v2
        with:
          repository: TamimiGitHub/solace-terraform-provisioning
          path: terraform
        
      - name: list files
        run: |
          pwd
          ls
          echo "==========="
          ls ../