name: Diff EP Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate diff
        uses: j-setiawan/ep-deployment-preview-action@v1
        with:
          application_version_id: 'c6e5koz6t7v'
          event_broker_id: '5c38mdgufxr'
          solace_cloud_token: ${{ secrets.SOLACE_CLOUD_TOKEN }}
      
      - name: Create PR comment
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('diff.txt', 'utf8');
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `\`\`\`\n${diff}\n\`\`\``
            });