name: Process post merge
on:
  push: 
    branches: [ master ]

jobs:
  import-asyncapi-file:
    runs-on: ubuntu-latest
    steps:
      - name: Import AsyncAPI spec file to EP
        run: echo "Importing file"

  sync-asyncapi-with-ep:
    needs: import-asyncapi-file
    runs-on: ubuntu-latest
    steps:
      - name: Sync AsyncAPI spec file with EP
        run: echo "Synching file with EP"
  
  commit-file:
    needs: sync-asyncapi-with-ep
    runs-on: ubuntu-latest
    steps:
      - name: Committing AsyncAPI spec file into repo
        run: echo "Commit file back to repo"

  trigger-jenkins:
    needs: commit-file
    runs-on: ubuntu-latest
    steps:
      - name: REST call to Jenkins
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://${{ secrets.JENKINS_HOST }}/job/build-awx-asyncapi-rest/buildWithParameters'
          method: 'POST'
          username: ${{ secrets.JENKINS_USER }}
          password: ${{ secrets.JENKINS_PASSWORD }}
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: '{"REPO_HTTP_URL": "value_1", "REPO_BRANCH": "value_2", "ASYNCAPI_FILE": "value_2", "BUILD_ENV": "value_2"}'