name: Process post merge
on:
  push: 
    branches: [ master ]

env:
  ASYNCAPI_FILE_PATH: 'none'
  CANCEL_WORKFLOW: ${{ false }}

jobs:
  asyncapi-present:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
            
      - name: Install asycnapi cli
        run: npm install -g @asyncapi/cli 
          
    # Get all files in commit
      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check if an AsycnAPI file is in commit
        run: |
          asyncapiFiles=()
          for changed_file in ${{ steps.files.outputs.all }}
          do
            if [[ ( ${changed_file} == *.yaml ) || ( ${changed_file} == *.yml ) || ( ${changed_file} == *.json ) ]]
            then
              asyncapi validate ${changed_file} &> check.txt
              # Check if the file is an asyncapi spec
              if ! grep -q "field is missing." check.txt; then
                asyncapiFiles+=("$changed_file")
                echo "ASYNCAPI_FILE_PATH=${changed_file}" >> $GITHUB_ENV
              fi
            fi
          done
          if [ ${#asyncapiFiles[@]} -eq 0 ]; then
            echo "Cancel workflow. No file found!"
            echo "CANCEL_WORKFLOW=true" >> $GITHUB_ENV
          fi

      - name: Cancel Workflow if no asyncAPI file present in PR
        if: env.CANCEL_WORKFLOW == 'true'
        uses: andymckay/cancel-action@0.2
      
      - id: set-async-path-var
        run: echo "::set-output name=ASYNCAPI_FILE_PATH::$ASYNCAPI_FILE_PATH"

  import-asyncapi-file:
    needs: asyncapi-present
    runs-on: ubuntu-latest
    steps:
      - name: Import AsyncAPI spec file to EP
        run: echo "Importing file"

  sync-asyncapi-with-ep:
    needs: import-asyncapi-file
    runs-on: ubuntu-latest
    steps:
      - name: Sync AsyncAPI spec file with EP
        run: echo "Synching file with EP"
      - name: Committing AsyncAPI spec file into repo
        run: echo "Commit file back to repo"

        
  
  # Trigger awx Jenkins job if an asyncapi spec file is present in commit merge
  trigger-jenkins:
    needs: asyncapi-present
    runs-on: ubuntu-latest
    steps:
      # - name: REST call to Jenkins
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'https://${{ secrets.JENKINS_HOST }}/job/build-awx-asyncapi-rest/buildWithParameters'
      #     method: 'POST'
      #     username: ${{ secrets.JENKINS_USER }}
      #     password: ${{ secrets.JENKINS_PASSWORD }}
      #     customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
      #     data: '{"parameter":[{"name":"REPO_HTTP_URL","value":"${{ github.event.repository.html_url }}"},{"name":"REPO_BRANCH","value":"${{ github.ref_name}}"},{"name":"ASYNCAPI_FILE","value":"${{needs.asyncapi-present.outputs.ASYNCAPI_FILE_PATH}}"},{"name":"BUILD_ENV","value":"test"}]}'
      - name: Trigger Jenkins 
        uses: enflo/jenkins-action@master
        with: 
          url: 'https://${{ secrets.JENKINS_HOST }}/job/build-awx-asyncapi-rest/buildWithParameters'
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_PASSWORD }}
          job: build-awx-asyncapi-rest
          parameters: REPO_HTTP_URL=${{ github.event.repository.html_url }}&REPO_BRANCH=${{ github.ref_name}}&ASYNCAPI_FILE=${{needs.asyncapi-present.outputs.ASYNCAPI_FILE_PATH}}&BUILD_ENV=test