name: Validate AsyncaPI spec file
on:
  pull_request: 
    branches: [ master ]

env:
  ASYNCAPI_FILE_PATH: "temp"

jobs:
  validate-asyncapi:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install asycnapi cli
        run: npm install -g @asyncapi/cli 

      # Check if a valid asyncapi file is in the PRs
      - id: async_spec_present
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.async_spec_present.outputs.all }}; do
            cat ${changed_file}
            asyncapi validate ${changed_file}
          done

      # Validate the asyncAPI file against best practices
      - name: Validate asyncapi spec file
        run: echo "validating file"

      - name: Attempt an import to EP
        run: echo "attempting to import the file to EP"