name: Validate AsyncaPI spec file
on:
  pull_request: 
    branches: [ master ]

env:
  ASYNCAPI_FILE_PATH: "none"

jobs:
  validate-asyncapi:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install asycnapi cli
        run: npm install -g @asyncapi/cli 

      # Check if a valid asyncapi file is in the PRs
      - id: async_spec_present
        uses: jitterbit/get-changed-files@v1

      # Validate the asyncAPI file against EP best practices
      - name: Validate asyncapi spec file
        run: |
          for changed_file in ${{ steps.async_spec_present.outputs.all }}; do
            asyncapi validate ${changed_file} >> output.txt
            if grep -q "successfully validateds!" "output.txt"; then
              export ASYNCAPI_FILE_PATH=${changed_file}
            fi
            env
          done

      - name: Cancel Workflow if no asyncAPI file present in PR
        if: env.ASYNCAPI_FILE_PATH == 'none' 
        uses: andymckay/cancel-action@0.2

      - name: Attempt an import to EP
        run: echo "attempting to import the file to EP"
        