name: Validate AsyncaPI spec file
on:
  pull_request: 
    branches: [ master ]

env:
  ASYNCAPI_FILE_PATH: "none"

jobs:
  validate-asyncapi:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install asycnapi cli
        run: npm install -g @asyncapi/cli 

      # Get all files in PR
      - id: async_spec_present
        uses: jitterbit/get-changed-files@v1

      # Check if AsyncAPI file in PR. If present, validate it
      - name: Validate asyncapi spec file
        run: |
          for changed_file in ${{ steps.async_spec_present.outputs.all }}; do
            asyncapi validate ${changed_file} >> output.txt
            
            if grep -q "ValidationError!" "output.txt"; then
              exit 1
            fi

            if grep -q "successfully validated!" "output.txt"; then
              export ASYNCAPI_FILE_PATH=${changed_file}
            fi
          done

      - name: Cancel Workflow if no asyncAPI file present in PR
        if: env.ASYNCAPI_FILE_PATH == 'none' 
        uses: andymckay/cancel-action@0.2

      # Import spec file to EP in checkmode
      - name: Attempt an import to EP
        run: echo "attempting to import the file to EP"
        