name: Validate AsyncaPI spec file
on:
  pull_request: 
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: List files
        run: find . -mindepth 3 -maxdepth 3 -type d

      - name: Validate asyncapi spec file
        run: echo "validating file"

      - name: Attempt an import to EP
        run: echo "attempting to import the file to EP"