name: Validate AsyncaPI spec file
on:
  pull_request: 
    branches: [ master ]

env:
  CANCEL_WORKFLOW: 'true'
jobs:
  asyncapi-present:
    runs-on: ubuntu-latest
    steps:
      - name: Install asycnapi cli
        run: npm install -g @asyncapi/cli 
          
    # Get all files in commit
      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check if AsycnAPI file in commit
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; dos
            asyncapi validate ${changed_file} &>> output.txt

            if grep -q "successfully validated!" "output.txt"; then
              export CANCEL_WORKFLOW='false'
            fi
          done
      - name: Should cancel?
        run: echo "$CANCEL_WORKFLOW"
        
      - name: Cancel Workflow if no asyncAPI file present in PR
        if: env.CANCEL_WORKFLOW == 'true' 
        uses: andymckay/cancel-action@0.2

  validate-asyncapi:
    runs-on: ubuntu-latest
    needs: asyncapi-present
    steps:

      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      # Import spec file to EP in checkmode
      - name: Attempt an import to EP
        run: echo "attempting to import the file to EP"
        