name: Export Codelabs
on:
  push:
    branches: [ master ]
    paths:
      - markdown/**

env:
  CHANGED_CODELABS: ''
jobs:
  Claat-Export:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      
      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          path: main

      - name: Checkout claat repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/google-tools
          path: google-tools
      
      - name: Build claat
        run: cd google-tools/claat; go build .
      
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: | 
            **.md
          path: main
        
      - name: Generate html codelabs and push to repo
        run: |
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            echo $file
            google-tools/claat/claat export -o main/codelabs/ main/$file
            echo "CHANGED_CODELABS=${CHANGED_CODELABS} $file" >> $GITHUB_ENV
          done

          cd main
          git status
          git remote -v
          ls codelabs
          git config user.name SollyBot
          git config user.email community@solace.com
          git commit -am "Adding ${{env.CHANGED_CODELABS}} html files"
          git push


      - name: Push updates to codelabs repo
        run: echo "Push updates to codelabs repo"
