name: Broken Links Checker
on:
  push:
    branches: [master]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.7
        with:
          args: --verbose --no-progress *.md *.js *.html
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
