name: Netllify Preview Builder
on:
  push: 
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          repository: SolaceDev/solace-dev-codelabs-site