name: Netlify Preview Builder
on:
  push: 
    branches: [ master ]

defaults:
  run:
    working-directory: site

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.2.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: site
          build_command: ls && npm run serve
      - name: Env variables
        run: |
          echo ${{env.GITHUB_SHA}}
          echo ${{env.GITHUB_REF}}