name: Netlify Preview Builder
on:
  push: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.1.7
        with:
          publish-dir: '${{github.action_path}}/site/dist'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: testing
        run: |
          cat ~/.netlify/config.json