name: Netlify Preview Builder
on:
  push: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.2.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}