name: Netlify Preview Builder
on:
  push: 
  # pull_request: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
      - name: build site
        run: cd site && gulp serve:dist --codelabs-dir=./solace-dev-codelabs/codelabs && rm dist/codelabs && cp -r solace-dev-codelabs/codelabs dist
      - name: Netlify Deploy
        uses: nwtgck/actions-netlify@v1.1.7
        with:
          publish-dir: './site/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}