name: New Action
on:
  push: 
    branches: [ master ]

env:
  SOLACE_CLOUD_TOKEN: ${{ secrets.SOLACE_CLOUD_TOKEN }}

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - uses: SolaceDev/solace-ep-provisioning-github-action@v1.1
        with:
          who-to-greet: 'Mona the Octocat'