name: Extract Application Version ID from mule xml
on:
  pull_request: 
    branches: [ master ]

# env:
#   MULE_FILE: 'none'

jobs:
  Pase_XML:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codelabs repo
        uses: actions/checkout@v2
        
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: | 
            **.xml

      - name: Read Mule XML content
        id: mule_xml
        run: |
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            # echo "MULE_FILE=$file" >> $GITHUB_ENV
            echo -e "xml<<EOF\n$(cat $file)\nEOF" >> $GITHUB_OUTPUT
            done

      - name: Extract Application Version ID from Mule config
        uses: tmelliottjr/extract-regex-action@v1.4.0
        id: epApplicationVersionId
        with:
          regex: '(?<=name=\"epApplicationVersionId\" value=\")(.*)(?=\")' 
          flags: "gm"
          input: ${{steps.mule_xml.outputs.xml}}

      # - name: Extract EP Applicatin Version ID from XML
      #   id: epApplicationVersionId
      #   uses: mavrosxristoforos/get-xml-info@1.2.1
      #   with:
      #     xml-file: ${{env.MULE_FILE}}
      #     xpath: "/mule/global-property[@name='epApplicationVersionId']/@value"

      - name: Echo Application Version ID
        run: echo ${{ steps.epApplicationVersionId.outputs.resultString }}