name: PR TEST
on:
  pull_request: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        run: echo ${{ github.event.pull_request.head }}