name: PR TEST
on:
  pull_request: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codelabs repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs
          path: codelabs
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Push updates to codelabs repo PAT
        run: |
          cd codelabs
          git config user.name solacecommunity-bot
          git config user.email community@solace.com
          echo "Test File" > test.txt
          git add test.txt
          git commit -m "Adding a test file"
          git push https://${{env.SOLACE_COMMUNITY_BOT_ULTIMATE}}@github.com/SolaceDev/solace-dev-codelabs