name: Extract Application Version ID from mule xml
on:
  pull_request: 
    branches: [ master ]

env:
  MULE_FILE_CONTENT: 'none'

jobs:
  Pase_XML:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codelabs repo
        uses: actions/checkout@v2
        
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: | 
            **.xml

      - name: Set path of xml file
        run: |
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            echo "MULE_FILE_CONTENT=`cat $file`" >> $GITHUB_ENV
          done

      - name: Extract Application Version ID from Mule config
        uses: tmelliottjr/extract-regex-action@v1.4.0
        id: epApplicationVersionId
        with:
          regex: '(?<=name=\"epApplicationVersionId\" value=\")(.*)(?=\")' 
          flags: "sgm"
          input: ${{ env.MULE_FILE_CONTENT }}

      # - name: Extract EP Applicatin Version ID from XML
      #   id: epApplicationVersionId
      #   uses: mavrosxristoforos/get-xml-info@1.2.1
      #   with:
      #     xml-file: ${{env.MULE_FILE_CONTENT}}
      #     xpath: "/mule/global-property[@name='epApplicationVersionId']/@value"

      - name: Echo Application Version ID
        run: echo ${{ steps.epApplicationVersionId.outputs.resultString }}