name: PR TEST
on:
  pull_request: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codelabs repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.SOLACE_COMMUNITY_BOT_ULTIMATE }}
          repository: SolaceDev/solace-dev-codelabs
          path: codelabs
        
      - name: Push updates to codelabs repo PAT
        run: |
          cd codelabs
          git config user.name solacecommunity-bot
          git config user.email community@solace.com
          echo "Test File" > test.txt
          git add test.txt
          git commit -m "Adding a test file"
          git push origin master
          # git push https://${{env.SOLACE_COMMUNITY_BOT_ULTIMATE}}@github.com/SolaceDev/solace-dev-codelabs
        env:
          GITHUB_TOKEN: ${{ secrets.SOLACE_COMMUNITY_BOT_ULTIMATE }}