# This workflow will be triggered on every commit merge to the defined branch
# Note : if an XML file is not present, the job is canceled

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# To get started, configure the following in your repos secrets https://docs.github.com/en/actions/security-guides/encrypted-secrets
# SOLACE_CLOUD_TOKEN: Solace Cloud Token
# TF_VAR_solace_url: SEMP URL for target broker provisioning
# TF_VAR_semp_username: SEMP username for target broker provisioning
# TF_VAR_semp_password: SEMP password for target broker provisioning
# SOL_MSG_VPN: Solace VPN

name: Promote and Provision Application Version ID from mule xml
on:
  pull_request: 
    branches: [ master ]

env: 
  SOLACE_MESSAGING_SERVICE: PRODUCTION-solace

jobs:
  promote_provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: | 
            src/main/mule/**.xml
      
      - name: Read Mule XML content
        id: mule_xml
        run: |
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            echo 'xml<<EOF' >> $GITHUB_OUTPUT
            echo $(cat $file) >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          done
      
      - name: Extract Application Version ID from Mule config
        if: ${{ steps.mule_xml.outputs.xml }}
        uses: tmelliottjr/extract-regex-action@v1.4.0
        id: epApplicationVersionId
        with:
          regex: '(?<=name=\"epApplicationVersionId\" value=\")(.*)(?=\")' 
          flags: "gm"
          input: ${{steps.mule_xml.outputs.xml}}

      - name: Echo Application Version ID
        run: echo ${{ steps.epApplicationVersionId.outputs.resultString }}

      - name: Promote and Provision Application
        if: ${{ steps.epApplicationVersionId.outputs.resultString }}
        uses: SolaceDev/solace-ep-provisioning-github-action@v1.10.1
        with:
          BROKER_TYPE: solace
          SOLACE_MESSAGING_SERVICE: ${{ env.SOLACE_MESSAGING_SERVICE }}
          SOLACE_CLOUD_TOKEN: ${{ secrets.SOLACE_CLOUD_TOKEN }}
          TF_VAR_solace_url: ${{ secrets.TF_VAR_solace_url }}
          TF_VAR_semp_username: ${{ secrets.TF_VAR_semp_username }}
          TF_VAR_semp_password: ${{ secrets.TF_VAR_semp_password }}
          SOL_MSG_VPN: ${{ secrets.SOL_MSG_VPN }}
          APPLICATION_VERSION_ID: ${{ steps.epApplicationVersionId.outputs.resultString }}