name: Update Codelabs Site
on:
  push: 
    branches: [ master ]

jobs:
  Checkout_Site_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update submodule
        run: |
          git submodule update --remote
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update submodule from github actions"
      - name: Push the changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          repository: SolaceDev/solace-dev-codelabs-site