name: Update Codelabs Site
on:
  push: 
    branches: [ master ]

jobs:
  Checkout_Site_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit the files
        run: |
          pwd;ls
          git submodule update --remote
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "Update submodule"
          git push https://#{{secrets.API_TOKEN}}@github.com/SolaceDev/solace-dev-codelabs-site.git origin master