# This workflow will trigger another workflow in another repo with payload passed as parameter

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# To get started, configure the following in your repos secrets https://docs.github.com/en/actions/security-guides/encrypted-secrets
# INFRA_REPO: the infrastructure repo in the form of <github_user>/<repo_name>
# WORKFLOW_PAT: Personal Access Token token for the destination repo for authentication. See more here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
## Note: The PAT should have workflow access enabled

name: Trigger Generate Implementation
on:
  pull_request: 
    branches: [ master ]

jobs:
  Trigger-Generate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger generate implementation 
        run: |
          spec="YOLO"
          curl -X POST -u "${{ github.actor }}:${{ secrets.WORKFLOW_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json"  \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ secrets.INFRA_REPO }}/dispatches \
            --data "{\"event_type\":\"trigger-event\",\"solace\":{\"asyncapi\":\"$spec\"}}"