name: Validate markdown file
on:
  pull_request: 
    branches: [ master ]

jobs:
  claat-export: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.17.0’
      - name: Install claat
        run: |
          go install github.com/googlecodelabs/tools/claat@latest