name: Validate markdown file
on:
  pull_request: 
    branches: [ master ]

jobs:
  claat-export: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.17.5’
      - name: Install claat
        run: |
          go install github.com/googlecodelabs/tools/claat@latest

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"

      - name: list changed files
        run: |
          echo ${{steps.changed-files.outputs.modified_files}}