name: Zip Workflow
on:
  push:
    tags:
     - "v*"

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Install the zip command line took from apk
      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip test
        run: |
          mkdir releases
          zip -qq -r releases/sig.zip images/email-sig-tamimi.png
          zip -qq -r releases/scripts.zip init.sh lychee.toml

      - name: Prepare archive
        uses: softprops/action-gh-release@v1
        with:
          files: release/*