name: Zip Workflow

on:
  pull_request:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Install the zip command line took from apk
      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip test
        run: |
          zip -qq -r sig.zip images/email-sig-tamimi.png
          zip -qq -r scripts.zip init.sh lychee.toml
      
      # This step lists all files in dir
      - name: List files
        run: ls -a

      # Unzip the sig.zip and scripts.zip files
      - name: Unzip files
        run: |
          unzip sig.zip -d SOURCE
          unzip scripts.zip -d SOURCE
          
      # List all files in the SOURCE directory
      - name: List files in SOURCE
        run: ls -a -R SOURCE